# Generated by Django 3.0.8 on 2021-05-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('book_image', models.ImageField(blank=True, upload_to='cart')),
                ('book_name', models.CharField(max_length=200)),
                ('book_price', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=200)),
                ('order_details', models.TextField()),
                ('date', models.CharField(default='', max_length=200)),
                ('qrcode', models.ImageField(blank=True, default='', upload_to='')),
                ('total', models.IntegerField(default=0)),
                ('TXNID', models.CharField(default='', max_length=200)),
                ('paymentmode', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
                ('BANKTXNID', models.CharField(default='', max_length=200)),
                ('invoice', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
