# Generated by Django 3.0.8 on 2021-05-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCommentPersonDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='comment_person_name')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BooksCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='books')),
                ('book_name', models.CharField(max_length=100)),
                ('book_offer_price', models.FloatField(default=0)),
                ('book_actual_price', models.FloatField(default=0)),
                ('book_author_name', models.CharField(default='', max_length=200)),
                ('book_publisher', models.CharField(default='', max_length=200)),
                ('book_language', models.CharField(default='', max_length=200)),
                ('book_total_pages', models.PositiveIntegerField(default=0)),
                ('book_published_year', models.CharField(default='', max_length=200)),
                ('book_details', models.TextField(default='')),
                ('books_data', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product.BooksCategories')),
            ],
        ),
    ]
